### PR TITLE
Minimal example

### PR DESCRIPTION
**Pull request by FredericBlum**
@LinguList Here comes the minimal example for reproducing the error.

### CODE REVIEW

**Comment by LinguList** [comment]
Did you see my remark in the issue? I think I have proposed a fix, right?

**Comment by FredericBlum** [comment]
I saw it but only got to test it now. Seems to work fine. We might change the condition so that this only is triggered when the length is exactly 1. This would then still throw an error when trying to give an empty sequence. Alternatively, we could throw a warning and proceed. Should I set such a thing up?

**Comment by LinguList** [comment]
Throwing errors for empty sequences is useful, in my experience. It is a symptom of empty rows in tables. Setting it up would be nice. Maybe, we should think of making a mini-package with tests. Did you test it on different data?

**Comment by LinguList** [comment]
The test is useful for grouped sounds, since it points to cases where grouping is too adhoc and not systematic. I had errors in the Karen data we use as example, and had to correct them.

**Comment by FredericBlum** [comment]
Do we still use the functions that we defined here, or do we switch to "linse"?

**Pull request closed without merging**
